package linux

type NR int

const (
	NR_none NR = iota
	NR_reject
	NR_ignore
	NR_io_setup
	NR_io_destroy
	NR_io_submit
	NR_io_cancel
	NR_io_getevents
	NR_setxattr
	NR_lsetxattr
	NR_fsetxattr
	NR_getxattr
	NR_lgetxattr
	NR_fgetxattr
	NR_listxattr
	NR_llistxattr
	NR_flistxattr
	NR_removexattr
	NR_lremovexattr
	NR_fremovexattr
	NR_getcwd
	NR_lookup_dcookie
	NR_eventfd2
	NR_epoll_create1
	NR_epoll_ctl
	NR_epoll_pwait
	NR_dup
	NR_dup3
	NR_fcntl
	NR_inotify_init1
	NR_inotify_add_watch
	NR_inotify_rm_watch
	NR_ioctl
	NR_ioprio_set
	NR_ioprio_get
	NR_flock
	NR_mknodat
	NR_mkdirat
	NR_unlinkat
	NR_symlinkat
	NR_linkat
	NR_renameat
	NR_umount2
	NR_mount
	NR_pivot_root
	NR_nfsservctl
	NR_statfs
	NR_fstatfs
	NR_truncate
	NR_ftruncate
	NR_fallocate
	NR_faccessat
	NR_chdir
	NR_fchdir
	NR_chroot
	NR_fchmod
	NR_fchmodat
	NR_fchownat
	NR_fchown
	NR_open
	NR_openat
	NR_close
	NR_vhangup
	NR_pipe2
	NR_quotactl
	NR_getdents64
	NR_lseek
	NR_read
	NR_write
	NR_readv
	NR_writev
	NR_pread64
	NR_pwrite64
	NR_preadv
	NR_pwritev
	NR_sendfile
	NR_pselect6
	NR_ppoll
	NR_signalfd4
	NR_vmsplice
	NR_splice
	NR_tee
	NR_readlinkat
	NR_fstatat64
	NR_fstat64
	NR_sync
	NR_fsync
	NR_fdatasync
	NR_sync_file_range
	NR_timerfd_create
	NR_timerfd_settime
	NR_timerfd_gettime
	NR_utimensat
	NR_acct
	NR_capget
	NR_capset
	NR_personality
	NR_exit
	NR_exit_group
	NR_waitid
	NR_set_tid_address
	NR_unshare
	NR_futex
	NR_set_robust_list
	NR_get_robust_list
	NR_nanosleep
	NR_getitimer
	NR_setitimer
	NR_kexec_load
	NR_init_module
	NR_delete_module
	NR_timer_create
	NR_timer_gettime
	NR_timer_getoverrun
	NR_timer_settime
	NR_timer_delete
	NR_clock_settime
	NR_clock_gettime
	NR_clock_getres
	NR_clock_nanosleep
	NR_syslog
	NR_ptrace
	NR_sched_setparam
	NR_sched_setscheduler
	NR_sched_getscheduler
	NR_sched_getparam
	NR_sched_setaffinity
	NR_sched_getaffinity
	NR_sched_yield
	NR_sched_get_priority_max
	NR_sched_get_priority_min
	NR_sched_rr_get_interval
	NR_restart_syscall
	NR_kill
	NR_tkill
	NR_tgkill
	NR_sigaltstack
	NR_rt_sigsuspend
	NR_rt_sigaction
	NR_rt_sigprocmask
	NR_rt_sigpending
	NR_rt_sigtimedwait
	NR_rt_sigqueueinfo
	NR_rt_sigreturn
	NR_setpriority
	NR_getpriority
	NR_reboot
	NR_setregid
	NR_setgid
	NR_setreuid
	NR_setuid
	NR_setresuid
	NR_getresuid
	NR_setresgid
	NR_getresgid
	NR_setfsuid
	NR_setfsgid
	NR_times
	NR_setpgid
	NR_getpgid
	NR_getsid
	NR_setsid
	NR_getgroups
	NR_setgroups
	NR_uname
	NR_sethostname
	NR_setdomainname
	NR_getrlimit
	NR_setrlimit
	NR_getrusage
	NR_umask
	NR_prctl
	NR_getcpu
	NR_gettimeofday
	NR_settimeofday
	NR_adjtimex
	NR_getpid
	NR_getppid
	NR_getuid
	NR_geteuid
	NR_getgid
	NR_getegid
	NR_gettid
	NR_sysinfo
	NR_mq_open
	NR_mq_unlink
	NR_mq_timedsend
	NR_mq_timedreceive
	NR_mq_notify
	NR_mq_getsetattr
	NR_msgget
	NR_msgctl
	NR_msgrcv
	NR_msgsnd
	NR_semget
	NR_semctl
	NR_semtimedop
	NR_semop
	NR_shmget
	NR_shmctl
	NR_shmat
	NR_shmdt
	NR_socket
	NR_socketpair
	NR_bind
	NR_listen
	NR_accept
	NR_connect
	NR_getsockname
	NR_getpeername
	NR_sendto
	NR_recvfrom
	NR_setsockopt
	NR_getsockopt
	NR_shutdown
	NR_sendmsg
	NR_recvmsg
	NR_readahead
	NR_brk
	NR_munmap
	NR_mremap
	NR_add_key
	NR_request_key
	NR_keyctl
	NR_clone
	NR_execve
	NR_mmap
	NR_mmap2
	NR_fadvise64
	NR_swapon
	NR_swapoff
	NR_mprotect
	NR_msync
	NR_mlock
	NR_munlock
	NR_mlockall
	NR_munlockall
	NR_mincore
	NR_madvise
	NR_remap_file_pages
	NR_mbind
	NR_get_mempolicy
	NR_set_mempolicy
	NR_migrate_pages
	NR_move_pages
	NR_rt_tgsigqueueinfo
	NR_perf_event_open
	NR_accept4
	NR_recvmmsg
	NR_arch_specific_syscall
	NR_wait4
	NR_prlimit64
	NR_fanotify_init
	NR_fanotify_mark
	NR_name_to_handle_at
	NR_open_by_handle_at
	NR_clock_adjtime
	NR_syncfs
	NR_setns
	NR_sendmmsg
	NR_process_vm_readv
	NR_process_vm_writev
	NR_kcmp
	NR_finit_module
	NR_sched_setattr
	NR_sched_getattr
	NR_renameat2
	NR_seccomp
	NR_getrandom
	NR_memfd_create
	NR_bpf
	NR_execveat
	NR_userfaultfd
	NR_membarrier
	NR_mlock2
	NR_copy_file_range
	NR_preadv2
	NR_pwritev2
	NR_pkey_mprotect
	NR_pkey_alloc
	NR_pkey_free
	NR_statx
	NR_io_pgetevents
	NR_rseq
	NR_kexec_file_load
)
